apply plugin: 'com.android.library'

group = 'expo.modules.adapters.clevertap'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()
useDefaultAndroidSdkVersions()

dependencies {
  implementation(project(':clevertap-react-native'))
  compileOnly("com.clevertap.android:push-templates:2.4.0")
}

android {
  namespace "expo.modules.adapters.clevertap"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    consumerProguardFiles 'consumer-rules.pro'
  }
  lint {
    abortOnError false
  }
}
